# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e495c0c3ae5a06f28c27740f08bc9088dc51432b498955b3434f2b1f12d7306e1641aeaee6599024b47a109482502c02883ce52d21ed5af54d8efa4b4de21f4b

test:
  secret_key_base: 5e80e23c06279b3c99e07aa1857254045853c341988028d464f8a1119b9e9fd72b68a5613c345dbdb11c717fbf0577c7054aa0a5588e9a5e965a7adcc41cb8d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
